// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkmdrqkjtsftiswjuera.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbWRycWtqdHNmdGlzd2p1ZXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDg1NDUsImV4cCI6MjA3MjUyNDU0NX0.ZA4QPuWEhoDTJ_tMZov4f21BqnE-guP8y0j_KNeQAnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});